import type { ITelegramClient } from "../../client.types.ts";
import type { ForumTopic, InputPeerLike } from "../../types/index.ts";
import { createDummyUpdate } from "../../updates/utils.ts";
import { isInputPeerChannel } from "../../utils/peer-utils.ts";
import { resolvePeer } from "../users/resolve-peer.ts";
/**
 * Delete a forum topic and all its history
 *
 * @param chat  Chat or user ID, username, phone number, `"me"` or `"self"`
 * @param topicId  ID of the topic (i.e. its top message ID)
 */
export async function deleteForumTopicHistory(client: ITelegramClient, chat: InputPeerLike, topicId: number | ForumTopic, params?: {
    /**
     * Whether to dispatch updates that will be generated by this call.
     * Doesn't follow `disableNoDispatch`
     */
    shouldDispatch?: true;
}): Promise<void> {
    const { shouldDispatch } = params ?? {};
    const peer = await resolvePeer(client, chat);
    const res = await client.call({
        _: 'messages.deleteTopicHistory',
        peer,
        topMsgId: typeof topicId === 'number' ? topicId : topicId.id,
    });
    if (!shouldDispatch) {
        client.handleClientUpdate(createDummyUpdate(res.pts, res.ptsCount, isInputPeerChannel(peer) ? peer.channelId : undefined));
    }
}
